[package]
name = "delta_test"
version = "0.0.2"
authors = ["John Wiegley"]
edition = "2018"

[[test]]
name = "sample-test"
path = "src/sample.rs"

[dev-dependencies]
serde = { version = "1.0", features = ["derive"] }
delta = { version = "0.0", features = ["derive"], path = "../delta" }
