[package]
name = "delta_test"
version = "0.1.0"
authors = ["John Wiegley"]
edition = "2018"

[[test]]
name = "sample-test"
path = "test/test.rs"

[dev-dependencies]
serde = { version = "1.0", features = ["derive"] }
delta = { version = "0.1", features = ["derive"], path = "../delta" }
