[package]
name = "delta-derive"
version = "0.0.1"
authors = ["John Wiegley"]
edition = "2018"

[lib]
proc-macro = true
path = "src/lib.rs"

[dependencies]
syn = "1.0"
quote = "1.0"
convert_case = "0.4"
proc-macro2 = "1.0"
